#!/usr/bin/env python3
"""
Generate one or more images via Luma's uni-1 API.

Brand contract: this script REFUSES to use any model other than `uni-1`.
Caleb's Luma deal mandates that every promotional image be generated by uni-1.
Do not relax this check.

Modes:
  --mode image       (default) text-to-image, optionally with --image-ref
                     references for style/subject grounding.
  --mode image_edit  edits a --source image (required) using --prompt;
                     --image-ref is optional. Output dimensions track the
                     source — --aspect-ratio is ignored for this mode.

Output contract:
  stdout: one JSON object per successfully generated variant, one per line
          {"variant": int, "path": str, "generation_id": str,
           "width": int, "height": int, "prompt": str, "mode": str,
           "aspect_ratio": str|null}
  stderr: human-readable progress + errors
  exit:   0 if at least one variant succeeded; 1 if all failed; 2 on bad args.

Stdlib only. No `requests`, no `python-dotenv`.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

API_BASE = "https://agents.lumalabs.ai/v1/generations"
ALLOWED_RATIOS = {"16:9", "1:1", "1:2", "1:3", "2:1", "2:3", "3:1", "3:2", "9:16"}
ALLOWED_MODES = {"image", "image_edit"}
LOCKED_MODEL = "uni-1"
POLL_INTERVAL_S = 3
POLL_TIMEOUT_S = 240  # ref-grounded gen takes ~50s; edits can take longer
MIN_DIMENSION = 1080  # Meta feed/single-image floor
MAX_REFS = 8  # Luma cap

# Auto-appended to every prompt unless --allow-chrome is set. Strips ALL
# platform / screenshot wrapper UI. The output should be the ad creative as
# it would be uploaded to Meta — the standalone image file, not a screenshot
# of how it gets displayed in-feed. Everything that Meta auto-adds when
# displaying the ad (brand row, body copy, link card, engagement) must be
# absent from the generated image.
NO_CHROME_SUFFIX = (
    "\n\n[NO PLATFORM CHROME] Render only the standalone ad creative (the static image uploaded to Meta), "
    "not a screenshot of how it displays in-feed. Exclude: iOS device chrome (status bar, home indicator); "
    "platform brand-row above the ad (avatar + handle + Sponsored / Saved label); post body / caption text; "
    "link-card footer (URL + headline + button); engagement rows (likes / comments / shares counts, "
    "Followed-by, View comments); action buttons (Like / Comment / Share / Save); comment input boxes; "
    "platform tab/nav bars (Instagram, Facebook, Twitter); Story chrome (progress bars, story header, "
    "swipe-up arrows). Just the standalone image."
)

SAFE_ZONE_SUFFIX = (
    "\n\n[EDGE-SAFE] All text, headlines, CTAs, table headers, sign/board content, product wordmarks, and "
    "key focal subjects must fit within the central 84% of the canvas (~8% padding from every edge). "
    "Backgrounds and divider lines may bleed; text and focal elements may NOT touch or extend off any edge. "
    "If a tall focal subject doesn't fit at the requested aspect ratio, scale it DOWN — never crop a "
    "headline, never let text run off-frame, never cut off the top/bottom of a sign, board, or product."
)

GLYPH_SAFETY_SUFFIX = (
    "\n\n[TEXT FIDELITY] Inside body-text blocks (chat bubbles, message threads, comment text, ChatGPT "
    "responses, dense paragraphs): plain words only — NO emoji, NO unicode glyphs, NO special characters "
    "mid-sentence. Emoji OK in headlines and short large-text positions where the prompt explicitly calls "
    "for them. Render the EXACT count of conversation elements the prompt specifies — do not invent "
    "additional comments, messages, replies, or responses."
)

MEDIA_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
}


def log(msg: str) -> None:
    print(msg, file=sys.stderr, flush=True)


def load_api_key(env_path: Path) -> str:
    """Parse LUMA_API_KEY from a .env file. No external deps."""
    if not env_path.exists():
        raise SystemExit(f"error: .env not found at {env_path}")
    for raw in env_path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        if k.strip() == "LUMA_API_KEY":
            v = v.strip().strip('"').strip("'")
            if not v:
                raise SystemExit("error: LUMA_API_KEY is empty in .env")
            return v
    raise SystemExit("error: LUMA_API_KEY not found in .env")


def slugify(text: str, max_len: int = 40) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:max_len] or "image"


def encode_image(path: Path) -> dict:
    """Read an image and return {data, media_type} for the Luma API."""
    if not path.exists():
        raise SystemExit(f"error: image not found: {path}")
    suffix = path.suffix.lower()
    mt = MEDIA_TYPES.get(suffix)
    if not mt:
        raise SystemExit(
            f"error: unsupported image extension '{suffix}' for {path}. "
            f"Supported: {sorted(MEDIA_TYPES)}"
        )
    data = base64.b64encode(path.read_bytes()).decode("ascii")
    return {"data": data, "media_type": mt}


def http_post_json(url: str, headers: dict, body: dict, timeout: int = 60) -> dict:
    req = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers=headers,
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")[:1000]
        raise RuntimeError(f"HTTP {e.code} from Luma: {detail}") from e


def http_get_json(url: str, headers: dict, timeout: int = 30) -> dict:
    req = urllib.request.Request(url, headers=headers, method="GET")
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def http_download(url: str, dest: Path, timeout: int = 120) -> None:
    req = urllib.request.Request(url, method="GET")
    with urllib.request.urlopen(req, timeout=timeout) as resp, dest.open("wb") as out:
        while chunk := resp.read(64 * 1024):
            out.write(chunk)


def probe_dimensions(path: Path) -> tuple[int, int]:
    """Return (width, height) using macOS `sips`. Falls back to (0, 0) on error."""
    try:
        out = subprocess.run(
            ["sips", "-g", "pixelWidth", "-g", "pixelHeight", str(path)],
            capture_output=True,
            text=True,
            timeout=10,
            check=True,
        ).stdout
        w = h = 0
        for line in out.splitlines():
            line = line.strip()
            if line.startswith("pixelWidth:"):
                w = int(line.split(":", 1)[1].strip())
            elif line.startswith("pixelHeight:"):
                h = int(line.split(":", 1)[1].strip())
        return w, h
    except Exception as e:  # noqa: BLE001
        log(f"warn: could not probe dimensions for {path}: {e}")
        return 0, 0


def submit(
    prompt: str,
    mode: str,
    aspect_ratio: str | None,
    source_obj: dict | None,
    ref_objs: list[dict],
    api_key: str,
    allow_chrome: bool = False,
) -> str:
    """Submit a generation request. Returns generation ID."""
    final_prompt = prompt
    if not allow_chrome:
        final_prompt += NO_CHROME_SUFFIX
    # Safe-zone + glyph-safety always on (no escape hatch — they fix real
    # rendering failures with no downside).
    final_prompt += SAFE_ZONE_SUFFIX
    final_prompt += GLYPH_SAFETY_SUFFIX
    body: dict = {
        "prompt": final_prompt,
        "model": LOCKED_MODEL,
        "type": mode,
    }
    if mode == "image":
        if not aspect_ratio:
            raise ValueError("aspect_ratio required for type=image")
        body["aspect_ratio"] = aspect_ratio
    elif mode == "image_edit":
        if not source_obj:
            raise ValueError("source required for type=image_edit")
        body["source"] = source_obj
    if ref_objs:
        body["image_ref"] = ref_objs

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    resp = http_post_json(API_BASE, headers, body)
    gen_id = resp.get("id")
    if not gen_id:
        raise RuntimeError(f"submit returned no id: {resp}")
    return gen_id


def poll(gen_id: str, api_key: str) -> str:
    """Poll until completed. Returns the signed image URL."""
    headers = {"Authorization": f"Bearer {api_key}", "Accept": "application/json"}
    deadline = time.monotonic() + POLL_TIMEOUT_S
    last_state = None
    while time.monotonic() < deadline:
        resp = http_get_json(f"{API_BASE}/{gen_id}", headers)
        state = resp.get("state")
        if state != last_state:
            log(f"  [{gen_id[:8]}] state={state}")
            last_state = state
        if state == "completed":
            outputs = resp.get("output") or []
            if not outputs or not outputs[0].get("url"):
                raise RuntimeError(f"completed but no output url: {resp}")
            return outputs[0]["url"]
        if state == "failed":
            raise RuntimeError(
                f"generation failed: {resp.get('failure_reason')} "
                f"(code={resp.get('failure_code')})"
            )
        time.sleep(POLL_INTERVAL_S)
    raise TimeoutError(f"generation {gen_id} did not complete in {POLL_TIMEOUT_S}s")


def generate_one(
    variant: int,
    prompt: str,
    mode: str,
    aspect_ratio: str | None,
    source_obj: dict | None,
    ref_objs: list[dict],
    out_dir: Path,
    slug: str,
    ts: str,
    api_key: str,
    allow_chrome: bool = False,
) -> dict:
    log(f"variant {variant}: submitting (mode={mode})…")
    gen_id = submit(prompt, mode, aspect_ratio, source_obj, ref_objs, api_key, allow_chrome)
    log(f"variant {variant}: id={gen_id}")
    url = poll(gen_id, api_key)
    dest = out_dir / f"{ts}-{slug}-v{variant}.png"
    log(f"variant {variant}: downloading -> {dest.name}")
    http_download(url, dest)
    w, h = probe_dimensions(dest)
    if w and h and (w < MIN_DIMENSION or h < MIN_DIMENSION):
        log(
            f"variant {variant}: WARNING image is {w}x{h}, below Meta's "
            f"{MIN_DIMENSION}x{MIN_DIMENSION} floor. Regenerate or upscale."
        )
    return {
        "variant": variant,
        "path": str(dest),
        "generation_id": gen_id,
        "width": w,
        "height": h,
        "prompt": prompt,
        "mode": mode,
        "aspect_ratio": aspect_ratio,
    }


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate uni-1 image(s). Brand contract: uni-1 only.",
    )
    p.add_argument("--prompt", required=True, help="Image prompt (post-rewrite).")
    p.add_argument(
        "--mode",
        default="image",
        choices=sorted(ALLOWED_MODES),
        help="image (default, text-to-image with optional refs) or image_edit "
        "(modify --source).",
    )
    p.add_argument(
        "--aspect-ratio",
        choices=sorted(ALLOWED_RATIOS),
        help="Required for --mode image. Ignored for --mode image_edit.",
    )
    p.add_argument("--n", type=int, default=1, help="Variant count, 1-5.")
    p.add_argument(
        "--out",
        type=Path,
        default=Path("./generated"),
        help="Output directory for PNGs.",
    )
    p.add_argument(
        "--image-ref",
        type=Path,
        action="append",
        default=[],
        metavar="PATH",
        help=(
            f"Reference image path (PNG/JPG/WEBP). Repeatable, max {MAX_REFS}. "
            "Used for style/subject grounding in --mode image, and as additional "
            "references in --mode image_edit."
        ),
    )
    p.add_argument(
        "--source",
        type=Path,
        metavar="PATH",
        help="Source image to edit. Required for --mode image_edit, rejected "
        "for --mode image.",
    )
    p.add_argument(
        "--model",
        default=LOCKED_MODEL,
        help=f"Locked to {LOCKED_MODEL} by brand contract.",
    )
    p.add_argument(
        "--env-file",
        type=Path,
        default=Path(".env"),
        help="Path to .env (default: ./.env).",
    )
    p.add_argument(
        "--allow-chrome",
        action="store_true",
        help="Allow platform/screenshot UI in the output (iOS chrome, "
        "Sponsored badges, engagement rows, etc.). Default is to strip "
        "all such UI so the output is the standalone ad creative.",
    )
    args = p.parse_args()

    if args.model != LOCKED_MODEL:
        log(
            f"error: brand contract violation — model must be '{LOCKED_MODEL}', "
            f"got '{args.model}'. Caleb's Luma brand deal requires every "
            f"promotional image be generated by uni-1. This script refuses."
        )
        return 2

    if not (1 <= args.n <= 5):
        log(f"error: --n must be 1..5 (got {args.n})")
        return 2

    if len(args.image_ref) > MAX_REFS:
        log(f"error: too many --image-ref ({len(args.image_ref)}); max is {MAX_REFS}")
        return 2

    if args.mode == "image":
        if args.source is not None:
            log("error: --source is not allowed with --mode image. "
                "Use --image-ref for guidance, or switch to --mode image_edit.")
            return 2
        if not args.aspect_ratio:
            log("error: --aspect-ratio is required for --mode image. "
                f"Choose one of {sorted(ALLOWED_RATIOS)}.")
            return 2
    elif args.mode == "image_edit":
        if args.source is None:
            log("error: --source is required for --mode image_edit.")
            return 2
        if args.aspect_ratio:
            log("warn: --aspect-ratio is ignored for --mode image_edit "
                "(output dimensions track the source).")

    api_key = load_api_key(args.env_file)
    args.out.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    slug = slugify(args.prompt)

    # Encode source + refs ONCE; the same payload is reused across all variants.
    source_obj = encode_image(args.source) if args.source else None
    ref_objs = [encode_image(p) for p in args.image_ref]
    if source_obj:
        log(f"source: {args.source.name} ({len(source_obj['data'])//1024} KB b64)")
    for i, (path, obj) in enumerate(zip(args.image_ref, ref_objs)):
        log(f"image_ref[{i}]: {path.name} ({len(obj['data'])//1024} KB b64)")

    aspect = args.aspect_ratio if args.mode == "image" else None
    chrome_state = "allowed" if args.allow_chrome else "stripped"
    log(
        f"generating {args.n} variant(s) mode={args.mode} "
        f"{'aspect=' + aspect if aspect else 'aspect=from-source'} "
        f"chrome={chrome_state} -> {args.out}/"
    )

    results: list[dict] = []
    errors: list[str] = []
    with ThreadPoolExecutor(max_workers=args.n) as ex:
        futures = {
            ex.submit(
                generate_one, i, args.prompt, args.mode, aspect,
                source_obj, ref_objs, args.out, slug, ts, api_key,
                args.allow_chrome,
            ): i
            for i in range(1, args.n + 1)
        }
        for fut in as_completed(futures):
            i = futures[fut]
            try:
                results.append(fut.result())
            except Exception as e:  # noqa: BLE001
                errors.append(f"variant {i}: {e}")
                log(f"variant {i}: FAILED — {e}")

    results.sort(key=lambda r: r["variant"])
    for r in results:
        print(json.dumps(r), flush=True)

    if not results:
        log(f"all {args.n} variant(s) failed")
        return 1
    if errors:
        log(f"{len(results)}/{args.n} succeeded, {len(errors)} failed")
    else:
        log(f"all {args.n} variant(s) succeeded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
